import { CategoryInfo, ToolItem } from '../types';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'ai',
    name: 'AI Tools',
    description: 'Smart AI utilities for writing, career building, and content generation.',
    iconName: 'Sparkles',
    color: 'from-blue-500 to-indigo-600',
    badgeColor: 'bg-indigo-50 dark:bg-indigo-950/50 text-indigo-600 dark:text-indigo-400 border-indigo-200 dark:border-indigo-800',
  },
  {
    id: 'pdf',
    name: 'PDF Tools',
    description: 'Convert, extract, merge, and manage PDF documents effortlessly.',
    iconName: 'FileText',
    color: 'from-rose-500 to-red-600',
    badgeColor: 'bg-rose-50 dark:bg-rose-950/50 text-rose-600 dark:text-rose-400 border-rose-200 dark:border-rose-800',
  },
  {
    id: 'image',
    name: 'Image Tools',
    description: 'Compress, resize, convert formats, and extract color palettes.',
    iconName: 'Image',
    color: 'from-emerald-500 to-teal-600',
    badgeColor: 'bg-emerald-50 dark:bg-emerald-950/50 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'text',
    name: 'Text Tools',
    description: 'Analyze word counts, change text case, and generate sample text.',
    iconName: 'Type',
    color: 'from-amber-500 to-orange-600',
    badgeColor: 'bg-amber-50 dark:bg-amber-950/50 text-amber-600 dark:text-amber-400 border-amber-200 dark:border-amber-800',
  },
  {
    id: 'calculator',
    name: 'Calculators',
    description: 'Calculate loan EMIs, exact age down to seconds, and percentages.',
    iconName: 'Calculator',
    color: 'from-violet-500 to-purple-600',
    badgeColor: 'bg-violet-50 dark:bg-violet-950/50 text-violet-600 dark:text-violet-400 border-violet-200 dark:border-violet-800',
  },
  {
    id: 'developer',
    name: 'Developer Tools',
    description: 'Generate custom QR codes, format JSON, and generate passwords.',
    iconName: 'Code',
    color: 'from-cyan-500 to-blue-600',
    badgeColor: 'bg-cyan-50 dark:bg-cyan-950/50 text-cyan-600 dark:text-cyan-400 border-cyan-200 dark:border-cyan-800',
  },
];

export const TOOLS: ToolItem[] = [
  // Popular Tools explicitly requested
  {
    id: 'ai-resume-builder',
    name: 'AI Resume Builder',
    category: 'ai',
    categoryName: 'AI Tools',
    description: 'Build professional resumes with AI-generated summaries, key achievements, and skills.',
    longDescription: 'Create executive-ready resumes in minutes. Our AI career assistant generates customized summary statements, high-impact bullet points, and industry skill recommendations tailored to your target job role.',
    iconName: 'FileBadge',
    isPopular: true,
    tags: ['ai', 'resume', 'cv', 'job', 'career', 'summary', 'builder', 'free'],
  },
  {
    id: 'ai-letter-writer',
    name: 'AI Letter Writer',
    category: 'ai',
    categoryName: 'AI Tools',
    description: 'Draft compelling cover letters, resignation notices, and formal requests in seconds.',
    longDescription: 'Never struggle with writing formal letters again. Choose your letter type (Cover Letter, Resignation, Thank You, Request), adjust tone, and let AI generate polished, persuasive correspondence.',
    iconName: 'PenTool',
    isPopular: true,
    tags: ['ai', 'letter', 'cover letter', 'resignation', 'writing', 'formal', 'email'],
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    category: 'developer',
    categoryName: 'Developer Tools',
    description: 'Create custom QR codes for URLs, text, Wi-Fi networks, emails, and phone numbers.',
    longDescription: 'Generate high-resolution QR codes instantaneously. Customize colors, sizing, error correction levels, and download cleanly in PNG or SVG vector formats with zero background noise.',
    iconName: 'QrCode',
    isPopular: true,
    tags: ['qr', 'generator', 'code', 'link', 'wifi', 'download', 'png', 'svg'],
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    category: 'image',
    categoryName: 'Image Tools',
    description: 'Reduce image file size up to 90% without sacrificing visible quality.',
    longDescription: 'Compress PNG, JPEG, and WEBP images directly inside your browser. Enjoy live side-by-side file size comparisons, adjustable quality sliders, and instant client-side downloads for optimal website speed.',
    iconName: 'Minimize2',
    isPopular: true,
    tags: ['image', 'compress', 'shrink', 'photo', 'png', 'jpg', 'webp', 'optimize'],
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    category: 'pdf',
    categoryName: 'PDF Tools',
    description: 'Extract text and content from PDF files and convert to editable document formats.',
    longDescription: 'Fast, browser-based PDF text extractor and converter. Upload your PDF file to extract clean formatted text, view layout structure, and download editable Word (.doc) or text (.txt) documents.',
    iconName: 'FileWord',
    isPopular: true,
    tags: ['pdf', 'word', 'convert', 'doc', 'text', 'extractor', 'editable'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    category: 'text',
    categoryName: 'Text Tools',
    description: 'Count words, characters, sentences, reading time, and keyword density in real-time.',
    longDescription: 'Comprehensive text analysis tool for writers, students, and SEO specialists. Instant word and character counts, reading & speaking time estimates, letter case conversions, and keyword frequency analysis.',
    iconName: 'FileText',
    isPopular: true,
    tags: ['word', 'counter', 'character', 'reading time', 'text', 'stats', 'seo'],
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    category: 'calculator',
    categoryName: 'Calculators',
    description: 'Calculate your exact age in years, months, days, hours, and seconds with birthday countdown.',
    longDescription: 'Discover your exact chronological age down to the second! Includes next birthday countdown, total days lived, day of the week you were born, zodiac sign, and fun life milestones.',
    iconName: 'Calendar',
    isPopular: true,
    tags: ['age', 'calculator', 'birthday', 'date', 'zodiac', 'years', 'days'],
  },
  {
    id: 'emi-calculator',
    name: 'EMI Calculator',
    category: 'calculator',
    categoryName: 'Calculators',
    description: 'Calculate monthly loan EMIs, interest payable, and total loan payment schedules.',
    longDescription: 'Plan home loans, car loans, and personal loans with precision. Get exact monthly EMI payments, interest vs principal breakdown charts, total payable amounts, and amortization schedules.',
    iconName: 'BadgePercent',
    isPopular: true,
    tags: ['emi', 'calculator', 'loan', 'interest', 'finance', 'home loan', 'bank', 'mortgage'],
  },
  {
    id: 'gst-calculator',
    name: 'GST Calculator',
    category: 'calculator',
    categoryName: 'Calculators',
    description: 'Calculate GST inclusive and exclusive amounts, CGST, SGST, IGST tax breakdowns, and PDF downloads.',
    longDescription: 'Fast, professional GST calculation tool supporting GST inclusive (tax extraction) and GST exclusive (add tax) modes across standard slab rates (3%, 5%, 12%, 18%, 28%) or custom rates with printable PDF receipts.',
    iconName: 'Receipt',
    isPopular: true,
    tags: ['gst', 'calculator', 'tax', 'finance', 'invoice', 'cgst', 'sgst', 'igst', 'vat'],
  },

  // Additional tools per category for complete depth
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    category: 'developer',
    categoryName: 'Developer Tools',
    description: 'Prettify, format, minify, and validate JSON code with line error markers.',
    longDescription: 'Format raw JSON into readable indented structures or minify it for API usage. Instant syntax validation, depth highlighting, key counts, and 1-click copy or download.',
    iconName: 'Braces',
    isPopular: false,
    tags: ['json', 'format', 'prettify', 'minify', 'validate', 'developer', 'code'],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'developer',
    categoryName: 'Developer Tools',
    description: 'Generate ultra-secure, randomized passwords (8–128 chars) with strength scoring and bulk options.',
    longDescription: 'Create cryptographically strong passwords. Adjust length from 8 to 128 characters, toggle uppercase, lowercase, numbers, and special symbols, check security strength, bulk generate passwords, and track recent history.',
    iconName: 'KeyRound',
    isPopular: true,
    tags: ['password', 'generator', 'security', 'key', 'random', 'strong', 'developer', 'bulk'],
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    category: 'image',
    categoryName: 'Image Tools',
    description: 'Resize JPG, PNG, and WebP images by width/height pixels or percentage scale.',
    longDescription: 'Resize photos and images in seconds with exact pixel dimensions or percentage scaling. Lock aspect ratio, preview before saving, and download in JPG, PNG, or WebP formats.',
    iconName: 'Scaling',
    isPopular: true,
    tags: ['image', 'resize', 'dimension', 'photo', 'aspect ratio', 'pixels', 'scale', 'jpg', 'png', 'webp'],
  },
  {
    id: 'color-picker',
    name: 'Color Palette & Picker',
    category: 'image',
    categoryName: 'Image Tools',
    description: 'Pick colors, convert HEX/RGB/HSL codes, and generate beautiful color palettes.',
    longDescription: 'Explore color harmonies including Complementary, Analogous, Triadic, and Monochromatic schemes. Eyedropper code selection, HEX/RGB/HSL conversions, and 1-click hex copy.',
    iconName: 'Palette',
    isPopular: false,
    tags: ['color', 'picker', 'palette', 'hex', 'rgb', 'hsl', 'design', 'eyedropper'],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    category: 'text',
    categoryName: 'Text Tools',
    description: 'Transform text to UPPERCASE, lowercase, Title Case, camelCase, kebab-case, and snake_case.',
    longDescription: 'Convert string cases instantly. Ideal for developers writing code variables or writers formatting article titles, headings, and clean URL slugs.',
    iconName: 'ArrowLeftRight',
    isPopular: false,
    tags: ['case', 'converter', 'uppercase', 'lowercase', 'titlecase', 'camelcase', 'kebab'],
  },
  {
    id: 'lorem-generator',
    name: 'Lorem Ipsum Generator',
    category: 'text',
    categoryName: 'Text Tools',
    description: 'Generate clean dummy placeholder text by paragraphs, sentences, or word counts.',
    longDescription: 'Generate standard Lorem Ipsum text for website layouts and mockups. Customize paragraph count, words per paragraph, start with "Lorem ipsum", or wrap in HTML tags.',
    iconName: 'AlignLeft',
    isPopular: false,
    tags: ['lorem', 'ipsum', 'dummy', 'placeholder', 'text', 'generator', 'mockup'],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    category: 'calculator',
    categoryName: 'Calculators',
    description: 'Calculate percentages, percent increases, percent decreases, and fraction conversions.',
    longDescription: 'Solve percentage problems instantly: find X% of Y, calculate what percentage X is of Y, compute percentage change/growth, and discount savings.',
    iconName: 'Percent',
    isPopular: false,
    tags: ['percent', 'percentage', 'calculator', 'math', 'discount', 'increase'],
  },
  {
    id: 'ai-prompt-enhancer',
    name: 'AI Prompt Generator',
    category: 'ai',
    categoryName: 'AI Tools',
    description: 'Optimize simple text ideas into detailed, high-performing prompts for Gemini, ChatGPT, & Claude.',
    longDescription: 'Turn vague 1-line ideas into structured, professional master prompts. Add role context, constraints, output formatting, tone, and examples for superior AI results.',
    iconName: 'Sparkle',
    isPopular: false,
    tags: ['ai', 'prompt', 'generator', 'enhancer', 'chatgpt', 'gemini', 'claude', 'master'],
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger & Combiner',
    category: 'pdf',
    categoryName: 'PDF Tools',
    description: 'Merge multiple PDF files into one combined document with drag-and-drop reordering.',
    longDescription: 'Combine multiple PDF documents into a single unified file in seconds. Drag and drop to reorder pages/files, preview page counts, and download 100% private merged PDFs.',
    iconName: 'Combine',
    isPopular: true,
    tags: ['pdf', 'merge', 'combine', 'organize', 'document', 'pdf-lib', 'join'],
  },
  {
    id: 'pdf-splitter',
    name: 'PDF Splitter & Page Extractor',
    category: 'pdf',
    categoryName: 'PDF Tools',
    description: 'Split PDF files by page range, select specific pages, or separate every page individually.',
    longDescription: 'Extract specific page ranges or split large PDF files into individual single-page documents with visual page selection and 100% browser-based privacy.',
    iconName: 'Scissors',
    isPopular: true,
    tags: ['pdf', 'split', 'extractor', 'separate', 'pages', 'cut', 'pdf-lib'],
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    category: 'pdf',
    categoryName: 'PDF Tools',
    description: 'Compress and reduce PDF file size with Low, Medium, or High compression levels.',
    longDescription: 'Reduce PDF document file size significantly while preserving text clarity and document quality. Select your desired compression level and download 100% private compressed PDFs.',
    iconName: 'Minimize2',
    isPopular: true,
    tags: ['pdf', 'compress', 'shrink', 'reducer', 'optimize', 'file size', 'pdf-lib'],
  },
];
